language: r
warnings_are_errors: true
sudo: required

r_github_packages:
  - smartinsightsfromdata/rpivotTable
  - trestletech/shinyAce
  - jimhester/covr
  - jeroenooms/jsonlite
  - rstudio/shiny
  - ramnathv/htmlwidgets
  - rstudio/DT

after_success:
  - Rscript -e 'library(covr);coveralls()'
